/* =====================================================================
   content.js — Questionnaire content in DE / FR / IT
   Wording taken from the official Wissenschaftsbarometer Schweiz 2022
   questionnaires (Universität Zürich). Only the items required for the
   segmentation are included, plus birth year, gender, education, canton.
   ===================================================================== */

const UI = {
  de: {
    langName: "Deutsch",
    start_title: "Wissenschaftsbarometer",
    start_sub: "Ein kurzer Fragebogen zu Ihrer Sicht auf Wissenschaft und Forschung.",
    start_intro: "Dieser Fragebogen dauert etwa 5 Minuten. Ihre Angaben werden vertraulich behandelt und ausschliesslich für die Auswertung dieser Erhebung verwendet. Es besteht keine Möglichkeit, Sie anhand Ihrer Antworten zu identifizieren.",
    start_button: "Fragebogen starten",
    next: "Weiter",
    back: "Zurück",
    submit: "Absenden",
    dont_know: "Weiss nicht",
    dk_legend: "? = Weiss nicht",
    page_of: "Seite {n} von {total}",
    unanswered: "{n} Frage(n) auf dieser Seite sind noch unbeantwortet.",
    proceed_anyway: "Trotzdem weiter",
    select_placeholder: "Bitte wählen …",
    no_answer: "Keine Angabe",
    thanks_title: "Vielen Dank!",
    thanks_sub: "Ihre Antworten wurden gespeichert.",
    thanks_result: "Auf Basis Ihrer Antworten gehören Sie zum folgenden Publikumssegment:",
    thanks_error: "Ihre Antworten konnten nicht gespeichert werden. Bitte prüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
    retry: "Erneut versuchen",
    saving: "Speichern …"
  },
  fr: {
    langName: "Français",
    start_title: "Baromètre scientifique",
    start_sub: "Un court questionnaire sur votre regard sur la science et la recherche.",
    start_intro: "Ce questionnaire dure environ 5 minutes. Vos données seront traitées de manière confidentielle et utilisées uniquement pour l’analyse de cette enquête. Il sera impossible de vous identifier à partir de vos réponses.",
    start_button: "Commencer le questionnaire",
    next: "Suivant",
    back: "Retour",
    submit: "Envoyer",
    dont_know: "Ne sait pas",
    dk_legend: "? = Ne sait pas",
    page_of: "Page {n} sur {total}",
    unanswered: "{n} question(s) de cette page restent sans réponse.",
    proceed_anyway: "Continuer quand même",
    select_placeholder: "Veuillez choisir …",
    no_answer: "Pas de réponse",
    thanks_title: "Merci beaucoup !",
    thanks_sub: "Vos réponses ont été enregistrées.",
    thanks_result: "D’après vos réponses, vous appartenez au segment de public suivant :",
    thanks_error: "Vos réponses n’ont pas pu être enregistrées. Veuillez vérifier votre connexion Internet et réessayer.",
    retry: "Réessayer",
    saving: "Enregistrement …"
  },
  it: {
    langName: "Italiano",
    start_title: "Barometro scientifico",
    start_sub: "Un breve questionario sulla Sua visione della scienza e della ricerca.",
    start_intro: "Questo questionario dura circa 5 minuti. I Suoi dati saranno trattati in modo confidenziale e utilizzati esclusivamente per l’analisi di questa indagine. Non sarà possibile identificarLa in base alle Sue risposte.",
    start_button: "Inizia il questionario",
    next: "Avanti",
    back: "Indietro",
    submit: "Invia",
    dont_know: "Non so",
    dk_legend: "? = Non so",
    page_of: "Pagina {n} di {total}",
    unanswered: "{n} domanda/e di questa pagina sono ancora senza risposta.",
    proceed_anyway: "Continua comunque",
    select_placeholder: "Selezioni …",
    no_answer: "Nessuna risposta",
    thanks_title: "Grazie mille!",
    thanks_sub: "Le Sue risposte sono state salvate.",
    thanks_result: "In base alle Sue risposte, Lei appartiene al seguente segmento di pubblico:",
    thanks_error: "Non è stato possibile salvare le Sue risposte. Controlli la connessione a Internet e riprovi.",
    retry: "Riprova",
    saving: "Salvataggio …"
  }
};

const SCALES = {
  interest: {
    de: ["überhaupt nicht", "sehr stark"],
    fr: ["pas du tout", "énormément"],
    it: ["per niente", "moltissimo"]
  },
  agree: {
    de: ["stimme überhaupt nicht zu", "stimme voll und ganz zu"],
    fr: ["n’approuve pas du tout", "approuve totalement"],
    it: ["non sono assolutamente d'accordo", "sono assolutamente d'accordo"]
  },
  trust: {
    de: ["sehr gering", "sehr hoch"],
    fr: ["très faible", "très élevé"],
    it: ["molto basso", "molto alto"]
  }
};

// Knowledge scale — compact labels for the horizontal matrix format.
// (FR/IT match the official questionnaires; DE compacted from the CATI wording,
// whose full meaning is given in the page intro.)
const KNOW_SCALE = {
  de: ["Sicher falsch", "Eher falsch", "Eher richtig", "Sicher richtig"],
  fr: ["Certainement faux", "Plutôt faux", "Plutôt juste", "Certainement juste"],
  it: ["Sicuramente errata", "Probabilmente errata", "Probabilmente esatta", "Sicuramente esatta"]
};

/* --- Items (id, type, scale) — texts per language --------------------- */

const QUESTIONS = [
  { id: "F0505", type: "scale5", scale: "interest",
    text: { de: "Wissenschaft und Forschung", fr: "Science et recherche", it: "Scienza e ricerca" } },

  { id: "F1504", type: "scale5", scale: "agree",
    text: { de: "Ich suche gezielt Informationen über Wissenschaft und Forschung.",
            fr: "Je cherche des informations sur la science et la recherche de façon ciblée.",
            it: "Cerco informazioni in modo mirato su scienza e ricerca." } },
  { id: "F1505", type: "scale5", scale: "agree",
    text: { de: "Es ist wichtig, dass man über Wissenschaft und Forschung informiert ist.",
            fr: "Il importe que l’on soit informé sur la science et la recherche.",
            it: "È importante essere informati su scienza e ricerca." } },

  { id: "F1801", type: "scale5", scale: "agree",
    text: { de: "Wissenschaftliche Forschung ist notwendig, auch wenn sich daraus kein unmittelbarer Nutzen ergibt.",
            fr: "La recherche scientifique est nécessaire, même s’il n’en résulte aucun avantage immédiat.",
            it: "La ricerca scientifica è necessaria anche se non produce un'utilità immediata." } },
  { id: "F1802", type: "scale5", scale: "agree",
    text: { de: "Wissenschaftliche Forschung sollte staatlich unterstützt werden.",
            fr: "La recherche scientifique devrait être soutenue par l’État.",
            it: "La ricerca scientifica dovrebbe essere sostenuta dallo Stato." } },
  { id: "F1803", type: "scale5", scale: "agree",
    text: { de: "Wissenschaftler sollten die Öffentlichkeit über ihre Arbeit informieren.",
            fr: "Les scientifiques devraient informer le public de leurs activités.",
            it: "Gli scienziati dovrebbero informare la gente sul loro lavoro." } },
  { id: "F1804", type: "scale5", scale: "agree",
    text: { de: "Wissenschaftler sollten mehr darauf hören, was einfache Leute denken.",
            fr: "Les scientifiques devraient plus écouter ce que les gens ordinaires pensent.",
            it: "Gli scienziati dovrebbero prestare più attenzione a quello che pensa la gente comune." } },
  { id: "F1806", type: "scale5", scale: "agree",
    text: { de: "Politische Entscheidungen sollten auf wissenschaftlichen Erkenntnissen beruhen.",
            fr: "Les décisions politiques devraient s’appuyer sur des bases scientifiques.",
            it: "Le decisioni politiche dovrebbero basarsi sulle conoscenze scientifiche." } },
  { id: "F1808", type: "scale5", scale: "agree",
    text: { de: "Leute wie ich sollten mitentscheiden, zu welchen Themen Wissenschaftler forschen.",
            fr: "Les personnes comme moi devraient prendre part à la décision sur les thèmes que les scientifiques doivent étudier.",
            it: "La gente come me dovrebbe partecipare alle decisioni sui temi oggetto di ricerca scientifica." } },
  { id: "F1809", type: "scale5", scale: "agree",
    text: { de: "Ich würde gern einmal in wissenschaftlichen Projekten mitforschen.",
            fr: "Je participerais volontiers un jour à des recherches sur des projets scientifiques.",
            it: "Mi piacerebbe partecipare una volta a qualche progetto scientifico." } },
  { id: "F1810", type: "scale5", scale: "agree",
    text: { de: "Wissenschaft und Forschung spielen in meinem Leben eine wichtige Rolle.",
            fr: "La science et la recherche jouent un rôle important dans ma vie.",
            it: "La scienza e la ricerca svolgono un ruolo importante nella mia vita." } },

  { id: "F1901", type: "scale5", scale: "agree",
    text: { de: "Wissenschaft und Forschung können jedes Problem lösen.",
            fr: "La science et la recherche peuvent résoudre chaque problème.",
            it: "La scienza e la ricerca possono risolvere ogni problema." } },
  { id: "F1902", type: "scale5", scale: "agree",
    text: { de: "Wissenschaft und Forschung verbessern unser Leben.",
            fr: "La science et la recherche améliorent notre vie.",
            it: "La scienza e la ricerca migliorano la nostra vita." } },
  { id: "F1903", type: "scale5", scale: "agree",
    text: { de: "Durch Wissenschaft und Forschung ändert sich unser Leben zu schnell.",
            fr: "La science et la recherche modifient notre mode de vie trop rapidement.",
            it: "Con la scienza e la ricerca la nostra vita cambia troppo velocemente." } },
  { id: "F1904", type: "scale5", scale: "agree",
    text: { de: "Der Nutzen von Wissenschaft und Forschung ist grösser als die möglicherweise auftretenden Schäden.",
            fr: "L’avantage de la science et de la recherche est plus important que les éventuels dégâts qui pourraient survenir.",
            it: "L'utilità della scienza e della ricerca è maggiore delle possibili conseguenze negative." } },
  { id: "F1905", type: "scale5", scale: "agree",
    text: { de: "Die Wissenschaft sollte ohne Einschränkung alles erforschen dürfen.",
            fr: "La science devrait pouvoir tout explorer sans limitation.",
            it: "La scienza dovrebbe poter fare ricerca su tutto senza limitazioni." } },
  { id: "F1906", type: "scale5", scale: "agree",
    text: { de: "Die Wissenschaft wird uns eines Tages ein vollständiges Bild davon vermitteln, wie Natur und Universum funktionieren.",
            fr: "La science nous transmettra un jour une image complète du fonctionnement de la nature et de l’univers.",
            it: "Un giorno la scienza ci fornirà un quadro completo del funzionamento della natura e dell'universo." } },
  { id: "F1907", type: "scale5", scale: "agree",
    text: { de: "Wir verlassen uns zu sehr auf die Wissenschaft.",
            fr: "Nous comptons trop sur la science.",
            it: "Ci affidiamo troppo alla scienza." } },

  { id: "F2003", type: "scale5", scale: "trust",
    text: { de: "Ihr Vertrauen in die Wissenschaft allgemein",
            fr: "Votre confiance dans la science en général",
            it: "La Sua fiducia nella scienza in generale" } },

  { id: "F2201", type: "know4",
    text: { de: "Die Kontinente, auf denen wir leben, bewegen sich schon seit Millionen von Jahren.",
            fr: "Les continents sur lesquels nous vivons se déplacent depuis des millions d’années.",
            it: "I continenti su cui viviamo si muovono già da milioni di anni." } },
  { id: "F2202", type: "know4",
    text: { de: "Elektronen sind kleiner als Atome.",
            fr: "Les électrons sont plus petits que les atomes.",
            it: "Gli elettroni sono più piccoli degli atomi." } },
  { id: "F2203", type: "know4",
    text: { de: "Antibiotika töten sowohl Viren als auch Bakterien.",
            fr: "Les antibiotiques tuent aussi bien les virus que les bactéries.",
            it: "Gli antibiotici uccidono sia i virus sia i batteri." } },
  { id: "F2204", type: "know4",
    text: { de: "Die Gene von der Mutter entscheiden, ob ein Kind ein Bube oder ein Mädchen wird.",
            fr: "Les gènes de la mère décident si un enfant sera un garçon ou une fille.",
            it: "I geni della madre determinano se nascerà un maschio o una femmina." } },
  { id: "F2211", type: "know4",
    text: { de: "Wissenschaftliche Theorien ändern sich nie.",
            fr: "Les théories scientifiques ne changent jamais.",
            it: "Le teorie scientifiche non cambiano mai." } },

  { id: "age", type: "age",
    text: { de: "In welchem Jahr sind Sie geboren?",
            fr: "Quelle est votre année de naissance ?",
            it: "In quale anno è nato/a?" } },
  { id: "gender", type: "gender",
    text: { de: "Geschlecht", fr: "Sexe", it: "Sesso" },
    options: { de: ["Männlich", "Weiblich", "Divers"],
               fr: ["Masculin", "Féminin", "Divers"],
               it: ["Maschile", "Femminile", "Altro"] } },
  { id: "education", type: "education",
    text: { de: "Welche Ausbildung haben Sie zuletzt abgeschlossen?",
            fr: "Quelle est la dernière formation que vous avez achevée ?",
            it: "Qual è l'ultima formazione da Lei conseguita?" },
    options: {
      de: ["Keine Ausbildung abgeschlossen", "Obligatorische Schule",
           "Diplommittelschule oder berufsvorbereitende Schule", "Berufslehre, Vollzeit-Berufsschule",
           "Maturitätsschule", "Lehrerseminar", "Höhere Fach- und Berufsausbildung",
           "Höhere Fachschule", "Fachhochschule", "Universität, Hochschule"],
      fr: ["Aucune scolarité achevée", "Scolarité obligatoire",
           "École de degré diplôme ou école de préparation professionnelle", "Apprentissage professionnel, école professionnelle à plein temps",
           "Maturité", "École normale", "Formation professionnelle supérieure",
           "École supérieure", "Haute école spécialisée", "Université, haute école"],
      it: ["Nessuna formazione conclusa", "Scuola dell'obbligo",
           "Diploma di scuola media o scuola professionale", "Tirocinio professionale, scuola professionale a tempo pieno",
           "Scuola di maturità", "Istituto magistrale", "Formazione specialistica o professionale superiore",
           "Scuola professionale superiore", "Scuola universitaria professionale", "Università, scuola universitaria"] } },
  { id: "canton", type: "canton",
    text: { de: "In welchem Kanton wohnen Sie?",
            fr: "Dans quel canton habitez-vous ?",
            it: "In quale Cantone abita?" } }
];

/* Swiss cantons: [code, DE, FR, IT] — plus "outside Switzerland". */
const CANTONS = [
  ["AG", "Aargau", "Argovie", "Argovia"],
  ["AI", "Appenzell Innerrhoden", "Appenzell Rhodes-Intérieures", "Appenzello Interno"],
  ["AR", "Appenzell Ausserrhoden", "Appenzell Rhodes-Extérieures", "Appenzello Esterno"],
  ["BE", "Bern", "Berne", "Berna"],
  ["BL", "Basel-Landschaft", "Bâle-Campagne", "Basilea Campagna"],
  ["BS", "Basel-Stadt", "Bâle-Ville", "Basilea Città"],
  ["FR", "Freiburg", "Fribourg", "Friburgo"],
  ["GE", "Genf", "Genève", "Ginevra"],
  ["GL", "Glarus", "Glaris", "Glarona"],
  ["GR", "Graubünden", "Grisons", "Grigioni"],
  ["JU", "Jura", "Jura", "Giura"],
  ["LU", "Luzern", "Lucerne", "Lucerna"],
  ["NE", "Neuenburg", "Neuchâtel", "Neuchâtel"],
  ["NW", "Nidwalden", "Nidwald", "Nidvaldo"],
  ["OW", "Obwalden", "Obwald", "Obvaldo"],
  ["SG", "St. Gallen", "Saint-Gall", "San Gallo"],
  ["SH", "Schaffhausen", "Schaffhouse", "Sciaffusa"],
  ["SO", "Solothurn", "Soleure", "Soletta"],
  ["SZ", "Schwyz", "Schwytz", "Svitto"],
  ["TG", "Thurgau", "Thurgovie", "Turgovia"],
  ["TI", "Tessin", "Tessin", "Ticino"],
  ["UR", "Uri", "Uri", "Uri"],
  ["VD", "Waadt", "Vaud", "Vaud"],
  ["VS", "Wallis", "Valais", "Vallese"],
  ["ZG", "Zug", "Zoug", "Zugo"],
  ["ZH", "Zürich", "Zurich", "Zurigo"]
];
const CANTON_OUTSIDE = { code: "EXT",
  de: "Ausserhalb der Schweiz", fr: "Hors de Suisse", it: "Fuori dalla Svizzera" };

/* --- Pages: 7 thematic screens --------------------------------------- */

const PAGES = [
  { key: "interest",
    title: { de: "Interesse", fr: "Intérêt", it: "Interesse" },
    intro: { de: "Bitte sagen Sie uns auf einer Skala von 1 bis 5, wie stark Sie sich für das folgende Thema interessieren.",
             fr: "Veuillez nous dire sur une échelle de 1 à 5 à quel point le sujet suivant vous intéresse.",
             it: "Ci indichi su una scala da 1 a 5 quanto è interessato/a al seguente tema." },
    items: ["F0505"] },
  { key: "information",
    title: { de: "Information", fr: "Information", it: "Informazione" },
    intro: { de: "Wie stark stimmen Sie den folgenden Aussagen zu?",
             fr: "Dans quelle mesure êtes-vous d’accord avec les affirmations suivantes ?",
             it: "Quanto è d’accordo con le seguenti affermazioni?" },
    items: ["F1504", "F1505"] },
  { key: "opinions",
    title: { de: "Meinungen zur Wissenschaft", fr: "Opinions sur la science", it: "Opinioni sulla scienza" },
    intro: { de: "Jetzt geht es um Ihre Meinung zu Wissenschaft und Forschung. Bitte sagen Sie uns, wie stark Sie den folgenden Aussagen zustimmen.",
             fr: "Nous nous intéressons à présent à votre opinion sur la science et la recherche. Veuillez nous dire à quel point vous approuvez les affirmations suivantes.",
             it: "Ora parliamo della Sua opinione su scienza e ricerca. Ci dica quanto è d’accordo con le seguenti affermazioni." },
    items: ["F1801", "F1802", "F1803", "F1804", "F1806", "F1808", "F1809", "F1810"] },
  { key: "effects",
    title: { de: "Auswirkungen der Wissenschaft", fr: "Effets de la science", it: "Effetti della scienza" },
    intro: { de: "Was glauben Sie: Welche Auswirkungen haben Wissenschaft und Forschung auf unser Leben?",
             fr: "Qu’en pensez-vous : quelles sont les répercussions de la science et de la recherche sur notre vie ?",
             it: "Secondo Lei, quali ripercussioni hanno scienza e ricerca sulla nostra vita?" },
    items: ["F1901", "F1902", "F1903", "F1904", "F1905", "F1906", "F1907"] },
  { key: "trust",
    title: { de: "Vertrauen", fr: "Confiance", it: "Fiducia" },
    intro: { de: "Auf einer Skala von 1 bis 5, wobei 1 «sehr gering» und 5 «sehr hoch» bedeutet: Wie hoch ist …",
             fr: "Sur une échelle de 1 à 5, où 1 signifie « très faible » et 5 « très élevé » : quel est le degré de …",
             it: "Su una scala da 1 a 5, in cui 1 indica « molto basso » e 5 « molto alto »: quanto è alta …" },
    items: ["F2003"] },
  { key: "knowledge",
    title: { de: "Wissensfragen", fr: "Questions de connaissances", it: "Domande di conoscenza" },
    intro: { de: "Die folgenden Aussagen kennen Sie vielleicht aus der Schule oder den Medien. Einige sind richtig, einige falsch. Bitte sagen Sie uns, ob die Aussage Ihrer Ansicht nach richtig oder falsch ist – und wie sicher Sie sind. Wenn Sie es nicht wissen, wählen Sie «?».",
             fr: "Vous connaissez peut-être les affirmations suivantes de l’école ou des médias. Certaines sont justes, d’autres fausses. Veuillez nous dire si, à votre avis, l’affirmation est juste ou fausse – et à quel point vous en êtes sûr(e). Si vous ne savez pas, choisissez « ? ».",
             it: "Le seguenti affermazioni Le sono forse note dalla scuola o dai media. Alcune sono esatte, altre errate. Ci dica se secondo Lei l’affermazione è esatta o errata – e quanto ne è sicuro/a. Se non lo sa, scelga « ? »." },
    items: ["F2201", "F2202", "F2203", "F2204", "F2211"] },
  { key: "about",
    title: { de: "Zu Ihrer Person", fr: "À propos de vous", it: "Su di Lei" },
    intro: { de: "Zum Abschluss haben wir noch einige Fragen zu Ihrer Person. Alle Angaben sind freiwillig.",
             fr: "Pour terminer, voici encore quelques questions vous concernant. Toutes les réponses sont facultatives.",
             it: "Per concludere, ancora qualche domanda su di Lei. Tutte le risposte sono facoltative." },
    items: ["age", "gender", "education", "canton"] }
];

const SEGMENT_DESC = {
  1: { de: "Sciencephiles — stark an Wissenschaft interessiert, informiert und mit hohem Vertrauen.",
       fr: "Sciencephiles — fortement intéressé·e·s par la science, informé·e·s et très confiant·e·s.",
       it: "Sciencephiles — fortemente interessati alla scienza, informati e con grande fiducia." },
  2: { de: "Critically Interested — interessiert, aber mit kritischer Distanz gegenüber Wissenschaft.",
       fr: "Critically Interested — intéressé·e·s, mais avec un recul critique envers la science.",
       it: "Critically Interested — interessati, ma con distanza critica verso la scienza." },
  3: { de: "Passive Supporters — grundsätzlich wohlgesonnen, aber wenig aktiv involviert.",
       fr: "Passive Supporters — plutôt favorables, mais peu impliqué·e·s activement.",
       it: "Passive Supporters — sostanzialmente favorevoli, ma poco coinvolti attivamente." },
  4: { de: "Disengaged — wenig Interesse an und geringe Nähe zu Wissenschaft.",
       fr: "Disengaged — peu d’intérêt et de proximité avec la science.",
       it: "Disengaged — scarso interesse e vicinanza alla scienza." }
};

if (typeof module !== "undefined") module.exports = { UI, SCALES, KNOW_SCALE, QUESTIONS, PAGES, CANTONS, CANTON_OUTSIDE, SEGMENT_DESC };
