/* =====================================================================
   content.js — Questionnaire content in DE / FR / IT / EN
   DE/FR/IT wording of segmentation items and most extra items taken
   from the official Wissenschaftsbarometer Schweiz 2022 questionnaires
   (Universität Zürich). EN wording and the seven extra interest topics
   are project translations (not validated instrument wording).
   ===================================================================== */

const LANGS = ["de", "fr", "it", "en"];

const UI = {
  de: {
    start_sub: "Vielen Dank für Ihren Besuch am Scientifica-Stand des Instituts für Kommunikationswissenschaft und Medienforschung (IKMZ) der Universität Zürich!",
    start_intro: "Dieser kurze Fragebogen dauert etwa 5–7 Minuten. Ihre Antworten werden vertraulich behandelt und ausschliesslich für die Auswertung dieser Erhebung verwendet. Die Angabe von Kontaktdaten am Ende ist freiwillig; sie wird nur für die Einladung zu einer möglichen Folgestudie verwendet.",
    start_button: "Fragebogen starten",
    next: "Weiter", back: "Zurück", submit: "Absenden",
    dont_know: "Weiss nicht",
    dont_know_na: "Weiss nicht / keine Angabe",
    yes: "Ja", no: "Nein", no_answer: "Keine Angabe",
    page_of: "Seite {n} von {total}",
    unanswered: "{n} Frage(n) auf dieser Seite sind noch unbeantwortet.",
    proceed_anyway: "Trotzdem weiter",
    select_placeholder: "Bitte wählen …",
    thanks_title: "Vielen Dank!",
    thanks_sub: "Ihre Antworten wurden gespeichert.",
    show_segment: "Mein Publikumssegment anzeigen",
    thanks_result: "Auf Basis Ihrer Antworten gehören Sie zum folgenden Publikumssegment:",
    thanks_error: "Ihre Antworten konnten nicht gespeichert werden. Bitte prüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
    retry: "Erneut versuchen", saving: "Speichern …",
    contact_email_q: "Wie lautet Ihre E-Mail-Adresse?",
    contact_post_q: "Wie lautet Ihre Postadresse?",
    contact_first: "Vorname", contact_last: "Name",
    contact_street: "Strasse / Nr.", contact_city: "PLZ / Ort"
  },
  fr: {
    start_sub: "Merci beaucoup de votre visite au stand Scientifica de l'Institut des sciences de la communication et de recherche sur les médias (IKMZ) de l'Université de Zurich !",
    start_intro: "Ce court questionnaire dure environ 5 à 7 minutes. Vos réponses seront traitées de manière confidentielle et utilisées uniquement pour l'analyse de cette enquête. L'indication de vos coordonnées à la fin est facultative ; elles ne seront utilisées que pour l'invitation à une éventuelle étude de suivi.",
    start_button: "Commencer le questionnaire",
    next: "Suivant", back: "Retour", submit: "Envoyer",
    dont_know: "Ne sait pas",
    dont_know_na: "Ne sait pas / pas de réponse",
    yes: "Oui", no: "Non", no_answer: "Pas de réponse",
    page_of: "Page {n} sur {total}",
    unanswered: "{n} question(s) de cette page restent sans réponse.",
    proceed_anyway: "Continuer quand même",
    select_placeholder: "Veuillez choisir …",
    thanks_title: "Merci beaucoup !",
    thanks_sub: "Vos réponses ont été enregistrées.",
    show_segment: "Afficher mon segment de public",
    thanks_result: "D'après vos réponses, vous appartenez au segment de public suivant :",
    thanks_error: "Vos réponses n'ont pas pu être enregistrées. Veuillez vérifier votre connexion Internet et réessayer.",
    retry: "Réessayer", saving: "Enregistrement …",
    contact_email_q: "Quelle est votre adresse e-mail ?",
    contact_post_q: "Quelle est votre adresse postale ?",
    contact_first: "Prénom", contact_last: "Nom",
    contact_street: "Rue / n°", contact_city: "NPA / localité"
  },
  it: {
    start_sub: "Grazie mille per la Sua visita allo stand Scientifica dell'Istituto di scienze della comunicazione e ricerca sui media (IKMZ) dell'Università di Zurigo!",
    start_intro: "Questo breve questionario dura circa 5–7 minuti. Le Sue risposte saranno trattate in modo confidenziale e utilizzate esclusivamente per l'analisi di questa indagine. L'indicazione dei dati di contatto alla fine è facoltativa; sarà utilizzata solo per l'invito a un eventuale studio di follow-up.",
    start_button: "Inizia il questionario",
    next: "Avanti", back: "Indietro", submit: "Invia",
    dont_know: "Non so",
    dont_know_na: "Non so / nessuna risposta",
    yes: "Sì", no: "No", no_answer: "Nessuna risposta",
    page_of: "Pagina {n} di {total}",
    unanswered: "{n} domanda/e di questa pagina sono ancora senza risposta.",
    proceed_anyway: "Continua comunque",
    select_placeholder: "Selezioni …",
    thanks_title: "Grazie mille!",
    thanks_sub: "Le Sue risposte sono state salvate.",
    show_segment: "Mostra il mio segmento di pubblico",
    thanks_result: "In base alle Sue risposte, Lei appartiene al seguente segmento di pubblico:",
    thanks_error: "Non è stato possibile salvare le Sue risposte. Controlli la connessione a Internet e riprovi.",
    retry: "Riprova", saving: "Salvataggio …",
    contact_email_q: "Qual è il Suo indirizzo e-mail?",
    contact_post_q: "Qual è il Suo indirizzo postale?",
    contact_first: "Nome", contact_last: "Cognome",
    contact_street: "Via / n.", contact_city: "NPA / località"
  },
  en: {
    start_sub: "Thank you very much for visiting the Scientifica stand of the Department of Communication and Media Research (IKMZ) at the University of Zurich!",
    start_intro: "This short questionnaire takes about 5–7 minutes. Your answers will be treated confidentially and used solely for the analysis of this survey. Providing contact details at the end is voluntary; they will only be used to invite you to a possible follow-up study.",
    start_button: "Start the questionnaire",
    next: "Next", back: "Back", submit: "Submit",
    dont_know: "Don't know",
    dont_know_na: "Don't know / no answer",
    yes: "Yes", no: "No", no_answer: "No answer",
    page_of: "Page {n} of {total}",
    unanswered: "{n} question(s) on this page are still unanswered.",
    proceed_anyway: "Continue anyway",
    select_placeholder: "Please choose …",
    thanks_title: "Thank you!",
    thanks_sub: "Your answers have been saved.",
    show_segment: "Show my audience segment",
    thanks_result: "Based on your answers, you belong to the following audience segment:",
    thanks_error: "Your answers could not be saved. Please check your internet connection and try again.",
    retry: "Try again", saving: "Saving …",
    contact_email_q: "What is your e-mail address?",
    contact_post_q: "What is your postal address?",
    contact_first: "First name", contact_last: "Last name",
    contact_street: "Street / no.", contact_city: "Postcode / town"
  }
};

const SCALES = {
  interest: {
    de: ["überhaupt nicht", "sehr stark"], fr: ["pas du tout", "énormément"],
    it: ["per niente", "moltissimo"], en: ["not at all", "very strongly"]
  },
  agree: {
    de: ["stimme überhaupt nicht zu", "stimme voll und ganz zu"],
    fr: ["n'approuve pas du tout", "approuve totalement"],
    it: ["non sono assolutamente d'accordo", "sono assolutamente d'accordo"],
    en: ["do not agree at all", "fully agree"]
  },
  trust: {
    de: ["sehr gering", "sehr hoch"], fr: ["très faible", "très élevé"],
    it: ["molto basso", "molto alto"], en: ["very low", "very high"]
  },
  religion: {
    de: ["überhaupt nicht religiös", "sehr religiös"],
    fr: ["pas du tout religieux", "très religieux"],
    it: ["per niente religioso/a", "molto religioso/a"],
    en: ["not at all religious", "very religious"]
  },
  politics: {
    de: ["sehr links", "sehr rechts"], fr: ["très à gauche", "très à droite"],
    it: ["molto di sinistra", "molto di destra"], en: ["very left-wing", "very right-wing"]
  }
};

const KNOW_SCALE = {
  de: ["Sicher falsch", "Eher falsch", "Eher richtig", "Sicher richtig"],
  fr: ["Certainement faux", "Plutôt faux", "Plutôt juste", "Certainement juste"],
  it: ["Sicuramente errata", "Probabilmente errata", "Probabilmente esatta", "Sicuramente esatta"],
  en: ["Definitely false", "Probably false", "Probably true", "Definitely true"]
};

/* --- Items ------------------------------------------------------------
   seg:true marks the 20 variables feeding the validated segmentation.
   Everything else is stored and monitored but never enters the scoring. */

const QUESTIONS = [
  /* Interest battery — general item feeds the segmentation, topics don't */
  { id: "F0505", type: "scale5", scale: "interest", seg: true,
    text: { de: "Wissenschaft und Forschung im Allgemeinen", fr: "Science et recherche en général",
            it: "Scienza e ricerca in generale", en: "Science and research in general" } },
  { id: "INT_MED", type: "scale5", scale: "interest",
    text: { de: "Medizin", fr: "Médecine", it: "Medicina", en: "Medicine" } },
  { id: "INT_ENV", type: "scale5", scale: "interest",
    text: { de: "Forschung zu Umwelt- und Energiefragen", fr: "Recherche sur les questions d'environnement et d'énergie",
            it: "Ricerca su questioni ambientali ed energetiche", en: "Research on environmental and energy issues" } },
  { id: "INT_BIO", type: "scale5", scale: "interest",
    text: { de: "Biologie", fr: "Biologie", it: "Biologia", en: "Biology" } },
  { id: "INT_SPACE", type: "scale5", scale: "interest",
    text: { de: "Raumfahrt", fr: "Astronautique", it: "Astronautica", en: "Space exploration" } },
  { id: "INT_POLSCI", type: "scale5", scale: "interest",
    text: { de: "Politikwissenschaft", fr: "Sciences politiques", it: "Scienze politiche", en: "Political science" } },
  { id: "INT_PSY", type: "scale5", scale: "interest",
    text: { de: "Psychologie", fr: "Psychologie", it: "Psicologia", en: "Psychology" } },
  { id: "INT_HIST", type: "scale5", scale: "interest",
    text: { de: "Geschichtswissenschaft", fr: "Sciences historiques", it: "Scienze storiche", en: "History" } },

  /* Information behaviour */
  { id: "F1504", type: "scale5", scale: "agree", seg: true,
    text: { de: "Ich suche gezielt Informationen über Wissenschaft und Forschung.",
            fr: "Je cherche des informations sur la science et la recherche de façon ciblée.",
            it: "Cerco informazioni in modo mirato su scienza e ricerca.",
            en: "I actively look for information about science and research." } },
  { id: "F1505", type: "scale5", scale: "agree", seg: true,
    text: { de: "Es ist wichtig, dass man über Wissenschaft und Forschung informiert ist.",
            fr: "Il importe que l'on soit informé sur la science et la recherche.",
            it: "È importante essere informati su scienza e ricerca.",
            en: "It is important to be informed about science and research." } },

  /* Opinions on science (goals) */
  { id: "F1801", type: "scale5", scale: "agree", seg: true,
    text: { de: "Wissenschaftliche Forschung ist notwendig, auch wenn sich daraus kein unmittelbarer Nutzen ergibt.",
            fr: "La recherche scientifique est nécessaire, même s'il n'en résulte aucun avantage immédiat.",
            it: "La ricerca scientifica è necessaria anche se non produce un'utilità immediata.",
            en: "Scientific research is necessary even if it brings no immediate benefit." } },
  { id: "F1802", type: "scale5", scale: "agree", seg: true,
    text: { de: "Wissenschaftliche Forschung sollte staatlich unterstützt werden.",
            fr: "La recherche scientifique devrait être soutenue par l'État.",
            it: "La ricerca scientifica dovrebbe essere sostenuta dallo Stato.",
            en: "Scientific research should be supported by the government." } },
  { id: "F1803", type: "scale5", scale: "agree", seg: true,
    text: { de: "Wissenschaftler sollten die Öffentlichkeit über ihre Arbeit informieren.",
            fr: "Les scientifiques devraient informer le public de leurs activités.",
            it: "Gli scienziati dovrebbero informare la gente sul loro lavoro.",
            en: "Scientists should inform the public about their work." } },
  { id: "F1804", type: "scale5", scale: "agree", seg: true,
    text: { de: "Wissenschaftler sollten mehr darauf hören, was einfache Leute denken.",
            fr: "Les scientifiques devraient plus écouter ce que les gens ordinaires pensent.",
            it: "Gli scienziati dovrebbero prestare più attenzione a quello che pensa la gente comune.",
            en: "Scientists should listen more to what ordinary people think." } },
  { id: "F1806", type: "scale5", scale: "agree", seg: true,
    text: { de: "Politische Entscheidungen sollten auf wissenschaftlichen Erkenntnissen beruhen.",
            fr: "Les décisions politiques devraient s'appuyer sur des bases scientifiques.",
            it: "Le decisioni politiche dovrebbero basarsi sulle conoscenze scientifiche.",
            en: "Political decisions should be based on scientific evidence." } },
  { id: "F1808", type: "scale5", scale: "agree", seg: true,
    text: { de: "Leute wie ich sollten mitentscheiden, zu welchen Themen Wissenschaftler forschen.",
            fr: "Les personnes comme moi devraient prendre part à la décision sur les thèmes que les scientifiques doivent étudier.",
            it: "La gente come me dovrebbe partecipare alle decisioni sui temi oggetto di ricerca scientifica.",
            en: "People like me should have a say in which topics scientists research." } },
  { id: "F1809", type: "scale5", scale: "agree", seg: true,
    text: { de: "Ich würde gern einmal in wissenschaftlichen Projekten mitforschen.",
            fr: "Je participerais volontiers un jour à des recherches sur des projets scientifiques.",
            it: "Mi piacerebbe partecipare una volta a qualche progetto scientifico.",
            en: "I would like to take part in scientific research projects one day." } },
  { id: "F1810", type: "scale5", scale: "agree", seg: true,
    text: { de: "Wissenschaft und Forschung spielen in meinem Leben eine wichtige Rolle.",
            fr: "La science et la recherche jouent un rôle important dans ma vie.",
            it: "La scienza e la ricerca svolgono un ruolo importante nella mia vita.",
            en: "Science and research play an important role in my life." } },

  /* Effects of science */
  { id: "F1901", type: "scale5", scale: "agree", seg: true,
    text: { de: "Wissenschaft und Forschung können jedes Problem lösen.",
            fr: "La science et la recherche peuvent résoudre chaque problème.",
            it: "La scienza e la ricerca possono risolvere ogni problema.",
            en: "Science and research can solve any problem." } },
  { id: "F1902", type: "scale5", scale: "agree", seg: true,
    text: { de: "Wissenschaft und Forschung verbessern unser Leben.",
            fr: "La science et la recherche améliorent notre vie.",
            it: "La scienza e la ricerca migliorano la nostra vita.",
            en: "Science and research improve our lives." } },
  { id: "F1903", type: "scale5", scale: "agree", seg: true,
    text: { de: "Durch Wissenschaft und Forschung ändert sich unser Leben zu schnell.",
            fr: "La science et la recherche modifient notre mode de vie trop rapidement.",
            it: "Con la scienza e la ricerca la nostra vita cambia troppo velocemente.",
            en: "Science and research make our lives change too quickly." } },
  { id: "F1904", type: "scale5", scale: "agree", seg: true,
    text: { de: "Der Nutzen von Wissenschaft und Forschung ist grösser als die möglicherweise auftretenden Schäden.",
            fr: "L'avantage de la science et de la recherche est plus important que les éventuels dégâts qui pourraient survenir.",
            it: "L'utilità della scienza e della ricerca è maggiore delle possibili conseguenze negative.",
            en: "The benefits of science and research outweigh the harm they might cause." } },
  { id: "F1905", type: "scale5", scale: "agree", seg: true,
    text: { de: "Die Wissenschaft sollte ohne Einschränkung alles erforschen dürfen.",
            fr: "La science devrait pouvoir tout explorer sans limitation.",
            it: "La scienza dovrebbe poter fare ricerca su tutto senza limitazioni.",
            en: "Science should be allowed to research anything without restriction." } },
  { id: "F1906", type: "scale5", scale: "agree", seg: true,
    text: { de: "Die Wissenschaft wird uns eines Tages ein vollständiges Bild davon vermitteln, wie Natur und Universum funktionieren.",
            fr: "La science nous transmettra un jour une image complète du fonctionnement de la nature et de l'univers.",
            it: "Un giorno la scienza ci fornirà un quadro completo del funzionamento della natura e dell'universo.",
            en: "One day science will give us a complete picture of how nature and the universe work." } },
  { id: "F1907", type: "scale5", scale: "agree", seg: true,
    text: { de: "Wir verlassen uns zu sehr auf die Wissenschaft.",
            fr: "Nous comptons trop sur la science.",
            it: "Ci affidiamo troppo alla scienza.",
            en: "We rely too much on science." } },

  /* Trust battery — only the "science in general" item feeds the segmentation */
  { id: "TR_UNI", type: "scale5", scale: "trust",
    text: { de: "… in Wissenschaftlerinnen und Wissenschaftler an Universitäten?",
            fr: "… les scientifiques au sein des universités ?",
            it: "… negli scienziati nelle università?",
            en: "… scientists at universities?" } },
  { id: "F2003", type: "scale5", scale: "trust", seg: true,
    text: { de: "… in die Wissenschaft allgemein?",
            fr: "… la science en général ?",
            it: "… nella scienza in generale?",
            en: "… science in general?" } },
  { id: "TR_MED", type: "scale5", scale: "trust",
    text: { de: "… in die Wissenschaftsberichterstattung von traditionellen Medien?",
            fr: "… le traitement des sujets scientifiques par les médias traditionnels ?",
            it: "… nella reportistica scientifica dei media tradizionali?",
            en: "… science reporting by traditional media?" } },

  /* Knowledge (scientific literacy) */
  { id: "F2201", type: "know4", seg: true,
    text: { de: "Die Kontinente, auf denen wir leben, bewegen sich schon seit Millionen von Jahren.",
            fr: "Les continents sur lesquels nous vivons se déplacent depuis des millions d'années.",
            it: "I continenti su cui viviamo si muovono già da milioni di anni.",
            en: "The continents on which we live have been moving for millions of years." } },
  { id: "F2202", type: "know4", seg: true,
    text: { de: "Elektronen sind kleiner als Atome.",
            fr: "Les électrons sont plus petits que les atomes.",
            it: "Gli elettroni sono più piccoli degli atomi.",
            en: "Electrons are smaller than atoms." } },
  { id: "F2203", type: "know4", seg: true,
    text: { de: "Antibiotika töten sowohl Viren als auch Bakterien.",
            fr: "Les antibiotiques tuent aussi bien les virus que les bactéries.",
            it: "Gli antibiotici uccidono sia i virus sia i batteri.",
            en: "Antibiotics kill viruses as well as bacteria." } },
  { id: "F2204", type: "know4", seg: true,
    text: { de: "Die Gene von der Mutter entscheiden, ob ein Kind ein Bube oder ein Mädchen wird.",
            fr: "Les gènes de la mère décident si un enfant sera un garçon ou une fille.",
            it: "I geni della madre determinano se nascerà un maschio o una femmina.",
            en: "The mother's genes decide whether a child will be a boy or a girl." } },
  { id: "F2211", type: "know4", seg: true,
    text: { de: "Wissenschaftliche Theorien ändern sich nie.",
            fr: "Les théories scientifiques ne changent jamais.",
            it: "Le teorie scientifiche non cambiano mai.",
            en: "Scientific theories never change." } },

  /* Connection to science (yes/no; scientists skip the following three) */
  { id: "SC_SELF", type: "yesno",
    text: { de: "Sind Sie selber Wissenschaftlerin oder Wissenschaftler?",
            fr: "Êtes-vous vous-même un ou une scientifique ?",
            it: "Lei è uno/a scienziato/a?",
            en: "Are you a scientist yourself?" } },
  { id: "SC_KNOW", type: "yesno",
    text: { de: "Kennen Sie eine Wissenschaftlerin oder einen Wissenschaftler persönlich?",
            fr: "Connaissez-vous un ou une scientifique ?",
            it: "Conosce personalmente uno/a scienziato/a?",
            en: "Do you personally know a scientist?" } },
  { id: "SC_JOB", type: "yesno",
    text: { de: "Haben Sie beruflich mit Wissenschaft zu tun?",
            fr: "Avez-vous professionnellement affaire avec un ou une scientifique ?",
            it: "Ha a che fare professionalmente con la scienza?",
            en: "Does your work involve science?" } },
  { id: "SC_FAM", type: "yesno",
    text: { de: "Haben Sie Familienmitglieder, die studiert haben oder noch studieren?",
            fr: "Avez-vous des membres de la famille qui ont étudié ou étudient encore ?",
            it: "Ha familiari che hanno studiato o studiano?",
            en: "Do you have family members who have studied or are currently studying?" } },

  /* Demographics */
  { id: "age", type: "age",
    text: { de: "In welchem Jahr sind Sie geboren?", fr: "Quelle est votre année de naissance ?",
            it: "In quale anno è nato/a?", en: "In which year were you born?" } },
  { id: "gender", type: "gender",
    text: { de: "Geschlecht", fr: "Sexe", it: "Sesso", en: "Gender" },
    options: { de: ["Männlich", "Weiblich", "Divers"], fr: ["Masculin", "Féminin", "Divers"],
               it: ["Maschile", "Femminile", "Altro"], en: ["Male", "Female", "Other"] } },
  { id: "education", type: "education",
    text: { de: "Welche Ausbildung haben Sie zuletzt abgeschlossen?",
            fr: "Quelle est la dernière formation que vous avez achevée ?",
            it: "Qual è l'ultima formazione da Lei conseguita?",
            en: "What is the highest level of education you have completed?" },
    options: {
      de: ["Keine Ausbildung abgeschlossen", "Obligatorische Schule",
           "Diplommittelschule oder berufsvorbereitende Schule", "Berufslehre, Vollzeit-Berufsschule",
           "Maturitätsschule", "Lehrerseminar", "Höhere Fach- und Berufsausbildung",
           "Höhere Fachschule", "Fachhochschule", "Universität, Hochschule"],
      fr: ["Aucune scolarité achevée", "Scolarité obligatoire",
           "École de degré diplôme ou école de préparation professionnelle", "Apprentissage professionnel, école professionnelle à plein temps",
           "Maturité", "École normale", "Formation professionnelle supérieure",
           "École supérieure", "Haute école spécialisée", "Université, haute école"],
      it: ["Nessuna formazione conclusa", "Scuola dell'obbligo",
           "Diploma di scuola media o scuola professionale", "Tirocinio professionale, scuola professionale a tempo pieno",
           "Scuola di maturità", "Istituto magistrale", "Formazione specialistica o professionale superiore",
           "Scuola professionale superiore", "Scuola universitaria professionale", "Università, scuola universitaria"],
      en: ["No completed education", "Compulsory school",
           "Specialised middle school or pre-vocational school", "Vocational apprenticeship, full-time vocational school",
           "Baccalaureate school", "Teacher training college", "Higher vocational education",
           "Professional college", "University of applied sciences", "University"] } },
  { id: "canton", type: "canton",
    text: { de: "In welchem Kanton wohnen Sie?", fr: "Dans quel canton habitez-vous ?",
            it: "In quale Cantone abita?", en: "In which canton do you live?" } },
  { id: "REL", type: "scale5", scale: "religion", dkna: true,
    text: { de: "Als wie religiös würden Sie sich beschreiben?",
            fr: "À quel point vous considérez-vous religieux/religieuse ?",
            it: "Quanto religioso/a si descriverebbe?",
            en: "How religious would you describe yourself as?" } },
  { id: "POL", type: "scale7", scale: "politics", dkna: true,
    text: { de: "Politische Standpunkte werden oft als «links» und «rechts» bezeichnet. Wie würden Sie Ihre eigene politische Einstellung einstufen?",
            fr: "Les positions politiques sont souvent qualifiées de « gauche » ou de « droite ». Comment situeriez-vous votre propre position politique ?",
            it: "Le posizioni politiche sono spesso definite di «sinistra» o di «destra». Come classificherebbe il Suo orientamento politico?",
            en: "Political views are often described as 'left' and 'right'. How would you rate your own political position?" } }
];

/* Swiss cantons: [code, DE, FR, IT, EN] */
const CANTONS = [
  ["AG", "Aargau", "Argovie", "Argovia", "Aargau"],
  ["AI", "Appenzell Innerrhoden", "Appenzell Rhodes-Intérieures", "Appenzello Interno", "Appenzell Innerrhoden"],
  ["AR", "Appenzell Ausserrhoden", "Appenzell Rhodes-Extérieures", "Appenzello Esterno", "Appenzell Ausserrhoden"],
  ["BE", "Bern", "Berne", "Berna", "Bern"],
  ["BL", "Basel-Landschaft", "Bâle-Campagne", "Basilea Campagna", "Basel-Landschaft"],
  ["BS", "Basel-Stadt", "Bâle-Ville", "Basilea Città", "Basel-Stadt"],
  ["FR", "Freiburg", "Fribourg", "Friburgo", "Fribourg"],
  ["GE", "Genf", "Genève", "Ginevra", "Geneva"],
  ["GL", "Glarus", "Glaris", "Glarona", "Glarus"],
  ["GR", "Graubünden", "Grisons", "Grigioni", "Grisons"],
  ["JU", "Jura", "Jura", "Giura", "Jura"],
  ["LU", "Luzern", "Lucerne", "Lucerna", "Lucerne"],
  ["NE", "Neuenburg", "Neuchâtel", "Neuchâtel", "Neuchâtel"],
  ["NW", "Nidwalden", "Nidwald", "Nidvaldo", "Nidwalden"],
  ["OW", "Obwalden", "Obwald", "Obvaldo", "Obwalden"],
  ["SG", "St. Gallen", "Saint-Gall", "San Gallo", "St. Gallen"],
  ["SH", "Schaffhausen", "Schaffhouse", "Sciaffusa", "Schaffhausen"],
  ["SO", "Solothurn", "Soleure", "Soletta", "Solothurn"],
  ["SZ", "Schwyz", "Schwytz", "Svitto", "Schwyz"],
  ["TG", "Thurgau", "Thurgovie", "Turgovia", "Thurgau"],
  ["TI", "Tessin", "Tessin", "Ticino", "Ticino"],
  ["UR", "Uri", "Uri", "Uri", "Uri"],
  ["VD", "Waadt", "Vaud", "Vaud", "Vaud"],
  ["VS", "Wallis", "Valais", "Vallese", "Valais"],
  ["ZG", "Zug", "Zoug", "Zugo", "Zug"],
  ["ZH", "Zürich", "Zurich", "Zurigo", "Zurich"]
];
const CANTON_OUTSIDE = { code: "EXT",
  de: "Ausserhalb der Schweiz", fr: "Hors de Suisse",
  it: "Fuori dalla Svizzera", en: "Outside Switzerland" };

/* Contact block (final page; template: follow-up recruitment) */
const CONTACT = {
  intro: {
    de: "Es ist möglich, dass es noch eine Folgestudie geben wird. Wir würden uns freuen, wenn Sie daran teilnehmen würden. Wenn Sie daran interessiert sind, würden wir Ihre Kontaktdaten aufnehmen und Ihnen eine Einladung zur Teilnahme per E-Mail oder Post schicken. Wäre dies möglich?",
    fr: "Il est possible qu'une étude de suivi ait lieu. Nous serions heureux que vous y participiez. Si cela vous intéresse, nous prendrions vos coordonnées afin de vous envoyer une invitation par e-mail ou par courrier. Serait-ce possible ?",
    it: "È possibile che ci sia uno studio di follow-up. Saremmo lieti se vi partecipasse. Se è interessato/a, prenderemmo i Suoi dati di contatto per inviarLe un invito per e-mail o per posta. Sarebbe possibile?",
    en: "There may be a follow-up study. We would be delighted if you took part. If you are interested, we would take your contact details and send you an invitation by e-mail or post. Would that be possible?"
  },
  options: {
    de: ["Ja, per E-Mail", "Ja, per Post (habe keine E-Mail-Adresse)", "Nein"],
    fr: ["Oui, par e-mail", "Oui, par courrier (je n'ai pas d'adresse e-mail)", "Non"],
    it: ["Sì, per e-mail", "Sì, per posta (non ho un indirizzo e-mail)", "No"],
    en: ["Yes, by e-mail", "Yes, by post (I have no e-mail address)", "No"]
  }
};

/* --- Pages ------------------------------------------------------------
   randomize:true shuffles the page's items once per session;
   pinFirst keeps the named item in first position. */

const PAGES = [
  { key: "interest", randomize: true, pinFirst: "F0505",
    title: { de: "Interesse", fr: "Intérêt", it: "Interesse", en: "Interest" },
    intro: { de: "Bitte sagen Sie uns auf einer Skala von 1 bis 5, wie stark Sie sich für die folgenden Themen interessieren.",
             fr: "Veuillez nous dire sur une échelle de 1 à 5 à quel point les sujets suivants vous intéressent.",
             it: "Ci indichi su una scala da 1 a 5 quanto è interessato/a ai seguenti temi.",
             en: "Please tell us on a scale from 1 to 5 how interested you are in the following topics." },
    items: ["F0505", "INT_MED", "INT_ENV", "INT_BIO", "INT_SPACE", "INT_POLSCI", "INT_PSY", "INT_HIST"] },
  { key: "information", randomize: true,
    title: { de: "Wissenschaftliche Information", fr: "Information scientifique",
             it: "Informazione scientifica", en: "Scientific information" },
    intro: { de: "Wie stark stimmen Sie den folgenden Aussagen zu?",
             fr: "Dans quelle mesure êtes-vous d'accord avec les affirmations suivantes ?",
             it: "Quanto è d'accordo con le seguenti affermazioni?",
             en: "How strongly do you agree with the following statements?" },
    items: ["F1504", "F1505"] },
  { key: "opinions", randomize: true,
    title: { de: "Meinung über Wissenschaft und Forschung", fr: "Opinion sur la science et la recherche",
             it: "Opinione su scienza e ricerca", en: "Opinion on science and research" },
    intro: { de: "Bitte sagen Sie uns, wie stark Sie den folgenden Aussagen zustimmen.",
             fr: "Veuillez nous dire à quel point vous approuvez les affirmations suivantes.",
             it: "Ci dica quanto è d'accordo con le seguenti affermazioni.",
             en: "Please tell us how strongly you agree with the following statements." },
    items: ["F1801", "F1802", "F1803", "F1804", "F1806", "F1808", "F1809", "F1810"] },
  { key: "effects", randomize: true,
    title: { de: "Auswirkungen der Wissenschaft", fr: "Effets de la science",
             it: "Effetti della scienza", en: "Effects of science" },
    intro: { de: "Was glauben Sie: Welche Auswirkungen haben Wissenschaft und Forschung auf unser Leben?",
             fr: "Qu'en pensez-vous : quelles sont les répercussions de la science et de la recherche sur notre vie ?",
             it: "Secondo Lei, quali ripercussioni hanno scienza e ricerca sulla nostra vita?",
             en: "What do you think: how do science and research affect our lives?" },
    items: ["F1901", "F1902", "F1903", "F1904", "F1905", "F1906", "F1907"] },
  { key: "trust", randomize: true,
    title: { de: "Vertrauen", fr: "Confiance", it: "Fiducia", en: "Trust" },
    intro: { de: "Wie hoch ist Ihr Vertrauen in …",
             fr: "Quel est le degré de votre confiance dans …",
             it: "Quanto è alta la Sua fiducia …",
             en: "How high is your trust in …" },
    items: ["TR_UNI", "F2003", "TR_MED"] },
  { key: "knowledge", randomize: true,
    title: { de: "Wissensfragen", fr: "Questions de connaissances", it: "Domande di conoscenza", en: "Knowledge questions" },
    intro: { de: "Die folgenden Aussagen kennen Sie vielleicht aus der Schule oder den Medien. Einige sind richtig, einige falsch. Bitte sagen Sie uns, ob die Aussage Ihrer Ansicht nach richtig oder falsch ist – und wie sicher Sie sind. Wenn Sie es nicht wissen, wählen Sie «?».",
             fr: "Vous connaissez peut-être les affirmations suivantes de l'école ou des médias. Certaines sont justes, d'autres fausses. Veuillez nous dire si, à votre avis, l'affirmation est juste ou fausse – et à quel point vous en êtes sûr(e). Si vous ne savez pas, choisissez « ? ».",
             it: "Le seguenti affermazioni Le sono forse note dalla scuola o dai media. Alcune sono esatte, altre errate. Ci dica se secondo Lei l'affermazione è esatta o errata – e quanto ne è sicuro/a. Se non lo sa, scelga « ? ».",
             en: "You may know the following statements from school or the media. Some are true, some are false. Please tell us whether you think each statement is true or false – and how sure you are. If you don't know, choose «?»." },
    items: ["F2201", "F2202", "F2203", "F2204", "F2211"] },
  { key: "connection",
    title: { de: "Bezug zur Wissenschaft", fr: "Rapport à la science",
             it: "Rapporto con la scienza", en: "Your connection to science" },
    intro: { de: "Es folgen einige Fragen zu Ihren persönlichen Berührungspunkten mit Wissenschaft.",
             fr: "Voici quelques questions sur vos points de contact personnels avec la science.",
             it: "Seguono alcune domande sui Suoi punti di contatto personali con la scienza.",
             en: "The following questions are about your personal points of contact with science." },
    items: ["SC_SELF", "SC_KNOW", "SC_JOB", "SC_FAM"] },
  { key: "about",
    title: { de: "Zu Ihrer Person", fr: "À propos de vous", it: "Su di Lei", en: "About you" },
    intro: { de: "Zum Abschluss haben wir noch einige Fragen zu Ihrer Person. Alle Angaben sind freiwillig.",
             fr: "Pour terminer, voici encore quelques questions vous concernant. Toutes les réponses sont facultatives.",
             it: "Per concludere, ancora qualche domanda su di Lei. Tutte le risposte sono facoltative.",
             en: "Finally, a few questions about yourself. All answers are voluntary." },
    items: ["age", "gender", "education", "canton", "REL", "POL"] },
  { key: "contact",
    title: { de: "Abschluss", fr: "Conclusion", it: "Conclusione", en: "Final question" },
    intro: null,
    items: [] }
];

/* Segment names per the official graphic (DE/FR); IT/EN project translations */
const SEGMENT_NAMES = {
  1: { de: "Sciencephile", fr: "Scientophiles", it: "Sciencephile", en: "Sciencephiles" },
  2: { de: "Kritisch Interessierte", fr: "Intéressés critiques", it: "Interessati critici", en: "Critically Interested" },
  3: { de: "Passive Unterstützer", fr: "Soutiens passifs", it: "Sostenitori passivi", en: "Passive Supporters" },
  4: { de: "Skeptische", fr: "Sceptiques", it: "Scettici", en: "Skeptics" }
};

const SEGMENT_DESC = {
  1: { de: "Sie zeichnen sich durch sehr hohes Vertrauen in die Wissenschaft und durchweg positive Einstellungen aus. Wissenschaft und Forschung sind Ihnen nah und spielen in Ihrem Leben eine wichtige Rolle.",
       fr: "Vous vous distinguez par une très grande confiance dans la science et des attitudes clairement positives. La science et la recherche vous sont proches et jouent un rôle important dans votre vie.",
       it: "Si distingue per una grandissima fiducia nella scienza e atteggiamenti decisamente positivi. La scienza e la ricerca Le sono vicine e svolgono un ruolo importante nella Sua vita.",
       en: "You stand out for your very high trust in science and consistently positive attitudes. Science and research feel close to you and play an important role in your life." },
  2: { de: "Sie stehen der Wissenschaft klar positiv gegenüber, bringen ihr aber etwas weniger Vertrauen entgegen. Zugleich sprechen Sie sich für klare Grenzen dessen aus, was Wissenschaft dürfen soll.",
       fr: "Vous avez une attitude clairement positive envers la science, mais vous lui accordez un peu moins de confiance. En même temps, vous êtes favorable à des limites claires de ce que la science peut faire.",
       it: "Ha un atteggiamento chiaramente positivo verso la scienza, ma le accorda un po' meno fiducia. Allo stesso tempo è favorevole a limiti chiari di ciò che la scienza può fare.",
       en: "You are clearly in favour of science, but place somewhat less trust in it. At the same time, you support clear limits on what science should be allowed to do." },
  3: { de: "Sie haben grundsätzlich positive Einstellungen zur Wissenschaft, betrachten sie aber eher aus der Distanz. Ihr persönliches Interesse an Wissenschaft und Forschung ist vergleichsweise gering.",
       fr: "Vous avez des attitudes globalement positives envers la science, mais vous la considérez plutôt à distance. Votre intérêt personnel pour la science et la recherche est comparativement faible.",
       it: "Ha atteggiamenti sostanzialmente positivi verso la scienza, ma la osserva piuttosto a distanza. Il Suo interesse personale per la scienza e la ricerca è relativamente basso.",
       en: "You hold broadly positive attitudes towards science, but tend to view it from a distance. Your personal interest in science and research is comparatively low." },
  4: { de: "Sie interessieren sich wenig für Wissenschaft und begegnen ihr eher distanziert und misstrauisch. Sie sprechen sich für klare Grenzen dessen aus, was Wissenschaft dürfen soll.",
       fr: "Vous vous intéressez peu à la science et l'abordez avec distance et une certaine méfiance. Vous êtes favorable à des limites claires de ce que la science peut faire.",
       it: "Si interessa poco alla scienza e la affronta con distanza e una certa diffidenza. È favorevole a limiti chiari di ciò che la scienza può fare.",
       en: "You take little interest in science and approach it with distance and some scepticism. You support clear limits on what science should be allowed to do." }
};

if (typeof module !== "undefined") module.exports = { LANGS, UI, SCALES, KNOW_SCALE, QUESTIONS, PAGES, CANTONS, CANTON_OUTSIDE, CONTACT, SEGMENT_NAMES, SEGMENT_DESC };
